#!/bin/bash

### select toolchain
## GCC 4.6 Linaro
## CUR_TC=/home/ruby/Toolchains/arm-eabi-linaro-4.6.2/bin/
## GCC 4.7 Linaro
##CUR_TC=/home/ruby/Toolchains/arm-linux-androideabi-4.7/bin/
## GCC 4.8 Linaro
##CUR_TC=/home/ruby/Toolchains/linaro_4.6.4/bin/
## GCC 4.8 Linaro
##CUR_TC=/home/ruby/Toolchains/linaro_4.8.3/bin/

### compile kernel
ARCH=arm CROSS_COMPILE=/home/ruby/Toolchains/arm-eabi-linaro-4.6.2/bin/arm-eabi- make -j8

echo "checking for compiled kernel..."
if [ -f arch/arm/boot/zImage ]
then

mkdir -p ../final_files


### copy zImage
cp arch/arm/boot/zImage ../final_files/.
cp arch/*/*/*.ko ../final_files/.
cp drivers/*/*.ko ../final_files/.
cp drivers/*/*/*.ko ../final_files/.
cp drivers/*/*/*/*.ko ../final_files/.
cp net/*/*.ko ../final_files/.
cp block/*.ko ../final_files/.
cp crypto/*.ko ../final_files/.
cp fs/*/*.ko ../final_files/.

echo "DONE"

fi
